### ISSUE TITLE
Tests failing due to missing test modules

### ISSUE THREAD

**Issue by carlsmedstad** [simonrob/pyasynchat#1]
Hey :wave:

I'm in the process of packaging this for Arch Linux and noticed that the tests are missing some of the modules required to run: 

```sh
$ python -m unittest discover -v
asynchat (unittest.loader._FailedTest.asynchat) ... ERROR
tests.test_asynchat (unittest.loader._FailedTest.tests.test_asynchat) ... ERROR

======================================================================
ERROR: asynchat (unittest.loader._FailedTest.asynchat)
----------------------------------------------------------------------
ImportError: Failed to import test module: asynchat
Traceback (most recent call last):
  File "/usr/lib/python3.12/unittest/loader.py", line 429, in _find_test_path
    package = self._get_module_from_name(name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/unittest/loader.py", line 339, in _get_module_from_name
    __import__(name)
  File "/build/python-pyasynchat/src/pyasynchat-1.0.4/asynchat/__init__.py", line 48, in <module>
    import asyncore
ModuleNotFoundError: No module named 'asyncore'


======================================================================
ERROR: tests.test_asynchat (unittest.loader._FailedTest.tests.test_asynchat)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_asynchat
Traceback (most recent call last):
  File "/usr/lib/python3.12/unittest/loader.py", line 396, in _find_test_path
    module = self._get_module_from_name(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/unittest/loader.py", line 339, in _get_module_from_name
    __import__(name)
  File "/build/python-pyasynchat/src/pyasynchat-1.0.4/tests/test_asynchat.py", line 3, in <module>
    from test import support
ModuleNotFoundError: No module named 'test'


----------------------------------------------------------------------
Ran 2 tests in 0.000s

FAILED (errors=2)
```

**Comment by yan12125** [comment]
> ModuleNotFoundError: No module named 'test'

This is an Arch-specific issue. The package `python-tests` is needed - see a working example at https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-pyasynchat

**Comment by carlsmedstad** [comment]
Ah, my bad, missed this. Thanks for letting me know!
